export const httpStatusCodes = [
  { statusCode: 100, message: 'Continue' },
  { statusCode: 101, message: 'Switching Protocols' },
  { statusCode: 102, message: 'Processing (WebDAV)' },
  { statusCode: 200, message: 'OK' },
  { statusCode: 201, message: 'Created' },
  { statusCode: 202, message: 'Accepted' },
  { statusCode: 203, message: 'Non-Authoritative Information' },
  { statusCode: 204, message: 'No Content' },
  { statusCode: 205, message: 'Reset Content' },
  { statusCode: 206, message: 'Partial Content' },
  { statusCode: 207, message: 'Multi-Status (WebDAV)' },
  { statusCode: 208, message: 'Already Reported (WebDAV)' },
  { statusCode: 300, message: 'Multiple Choices' },
  { statusCode: 301, message: 'Moved Permanently' },
  { statusCode: 302, message: 'Found' },
  { statusCode: 303, message: 'See Other' },
  { statusCode: 304, message: 'Not Modified' },
  { statusCode: 305, message: 'Use Proxy' },
  { statusCode: 307, message: 'Temporary Redirect' },
  { statusCode: 308, message: 'Permanent Redirect (experimental)' },
  { statusCode: 400, message: 'Bad Request' },
  { statusCode: 401, message: 'Unauthorized' },
  { statusCode: 402, message: 'Payment Required' },
  { statusCode: 403, message: 'Forbidden' },
  { statusCode: 404, message: 'Not Found' },
  { statusCode: 405, message: 'Method Not Allowed' },
  { statusCode: 406, message: 'Not Acceptable' },
  { statusCode: 407, message: 'Proxy Authentication Required' },
  { statusCode: 408, message: 'Request Timeout' },
  { statusCode: 409, message: 'Conflict' },
  { statusCode: 410, message: 'Gone' },
  { statusCode: 411, message: 'Length Required' },
  { statusCode: 412, message: 'Precondition Failed' },
  { statusCode: 413, message: 'Request Entity Too Large' },
  { statusCode: 414, message: 'Request-URI Too Long' },
  { statusCode: 415, message: 'Unsupported Media Type' },
  { statusCode: 416, message: 'Requested Range Not Satisfiable' },
  { statusCode: 417, message: 'Expectation Failed' },
  { statusCode: 418, message: "I'm a teapot (RFC 2324)" },
  { statusCode: 420, message: 'Enhance Your Calm(Twitter)' },
  { statusCode: 422, message: 'Unprocessable Entity (WebDAV)' },
  { statusCode: 423, message: 'Locked (WebDAV)' },
  { statusCode: 424, message: 'Failed Dependency (WebDAV)' },
  { statusCode: 425, message: 'Reserved for WebDAV' },
  { statusCode: 426, message: 'Upgrade Required' },
  { statusCode: 428, message: 'Precondition Required' },
  { statusCode: 429, message: 'Too Many Requests' },
  { statusCode: 431, message: 'Request Header Fields Too Large' },
  { statusCode: 444, message: 'No Response (Nginx)' },
  { statusCode: 449, message: 'Retry With (Microsoft)' },
  {
    statusCode: 450,
    message: 'Blocked by Windows Parental Controls (Microsoft)',
  },
  { statusCode: 451, message: 'Unavailable For Legal Reasons' },
  { statusCode: 499, message: 'Client Closed Request (Nginx)' },
  { statusCode: 500, message: 'Internal Server Error' },
  { statusCode: 501, message: 'Not Implemented' },
  { statusCode: 502, message: 'Bad Gateway' },
  { statusCode: 503, message: 'Service Unavailable' },
  { statusCode: 504, message: 'Gateway Timeout' },
  { statusCode: 505, message: 'HTTP Version Not Supported' },
  { statusCode: 506, message: 'Variant Also Negotiates (Experimental)' },
  { statusCode: 507, message: 'Insufficient Storage (WebDAV)' },
  { statusCode: 508, message: 'Loop Detected (WebDAV)' },
  { statusCode: 509, message: 'Bandwidth Limit Exceeded (Apache)' },
  { statusCode: 510, message: 'Not Extended' },
  { statusCode: 511, message: 'Network Authentication Required' },
];
